name: Setup Python and uv
description: |
  Consistently installs python across this project. Should be used as a
  replacement for direct calls to actions/setup-python.

  Serves as the single place to update python versions over time across the
  project.
outputs:
  python-version:
    description: Version of Python installed
    value: ${{ steps.setup-python.outputs.python-version }}
runs:
  using: composite
  steps:
  - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
    with:
      python-version: '3.13'
  - uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
